import './utils/polyfills.js';
import './global.js';
import { App } from './app/App.js';
import { RAF } from './systems/RAF.js';
import { registerSystem, systems } from './systems/registrar.js';
import { Cache, Loader } from './systems/Loader.js';
import { Input } from './systems/Input.js';
import './systems/Timer.js';
import { TweenManager, Easing, Interpolation } from './systems/Tween.js';
import { CanvasBuffer } from './utils/CanvasBuffer';
import { EventEmitter } from './utils/EventEmitter';

Tiny.App = App;
Tiny.RAF = RAF;
Tiny.registerSystem = registerSystem;
Tiny.systems = systems;
Tiny.TweenManager = TweenManager;
Tiny.Cache = Cache;
Tiny.Loader = Loader;
Tiny.Easing = Easing;
Tiny.Interpolation = Interpolation;
Tiny.Input = Input;
Tiny.CanvasBuffer = CanvasBuffer;
Tiny.EventEmitter = EventEmitter;
