import './utils/polyfills';
import './global';
import { App } from './app/App';
import { RAF } from './systems/RAF';
import { registerSystem, systems } from './systems/registrar';
import { Cache, Loader } from './systems/Loader';
import { Input } from './systems/Input';
import './systems/Timer';
import { TweenManager, Easing, Interpolation } from './systems/Tween';
import { CanvasBuffer } from './utils/CanvasBuffer';
import { EventEmitter } from './utils/EventEmitter';
import { _Math } from './math/Math';

Tiny.App = App;
Tiny.RAF = RAF;
Tiny.registerSystem = registerSystem;
Tiny.systems = systems;
Tiny.TweenManager = TweenManager;
Tiny.Cache = Cache;
Tiny.Loader = Loader;
Tiny.Easing = Easing;
Tiny.Interpolation = Interpolation;
Tiny.Input = Input;
Tiny.CanvasBuffer = CanvasBuffer;
Tiny.EventEmitter = EventEmitter;
Tiny.Math = _Math;
